project_name             = "twin"
environment              = "dev"
# Q42 https://edwarddonner.com/faq — prefer global Nova 2 Lite (pooled quota). Empty = Bedrock client uses Lambda region.
bedrock_runtime_region   = ""
bedrock_model_id         = "global.amazon.nova-2-lite-v1:0"
lambda_timeout           = 60
api_throttle_burst_limit = 10
api_throttle_rate_limit  = 5
use_custom_domain        = false
root_domain              = ""